# Generated by Django 5.1.7 on 2025-03-27 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tag_bookmark_lesson_bookmark_user_lesson_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.comment'),
        ),
    ]
